# Site settings
title: Tiger Cross
description: My personal website with links to my various media accounts
baseurl: "/Personal-Website" # the subpath of your site, e.g. /blog
url: "https://tigercross.co.uk" # the base hostname & protocol for your site

# User settings
username: Tiger Cross
user_description: Check out my CV, Github, Linkedin and more!
user_title: Software Engineer 
email: tiger.cross17@gmail.com
github_username:  lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
