# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Tiger Cross 
description: "My personal portfolio"
keywords: "Jekyll, personal, SEO, web, cv, portfolio, social, linkedin, github"
url: http://tigercross.co.uk
baseurl: "/home"

google_analytics: UA-52446115-1
repo: http://github.com/Tiger-Cross/Personal-Website
disqus_shortname: "tiger"
disqus_site_shortname: "tiger"

# Author settings
author:
  name: Tiger Cross
  job: Software Engineer
  bio: "TODO: Bio"
  thumb: /images/author.jpg
  email: tiger.cross17@gmail.com
  url: https://tigercross.co.uk/
  github: https://github.com/Tiger-Cross
  facebook: https://facebook.com/
  linkedin: https://linkedin.com/in/Tiger-Cross

# navbar pages
navbar:
  - slug: icons
    title: Icons

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
